import { useState, useRef, useEffect } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import toast from 'react-hot-toast'
import { verifyMfaWithGateway } from '@/lib/security/authGatewayClient'

interface LocationState {
  aal1AccessToken?: string
  factorId?: string
}

export function TwoFactorVerification() {
  const navigate = useNavigate()
  const location = useLocation()
  const state = (location.state ?? {}) as LocationState

  const aal1AccessToken = state.aal1AccessToken ?? null
  const factorId = state.factorId ?? null

  const [codes, setCodes] = useState(['', '', '', '', '', ''])
  const [isLoading, setIsLoading] = useState(false)
  const [resendCountdown, setResendCountdown] = useState(0)
  const inputRefs = useRef<(HTMLInputElement | null)[]>([])

  // Guard: if this page is accessed directly without MFA state, redirect to login
  useEffect(() => {
    if (!aal1AccessToken || !factorId) {
      toast.error('Session expired. Please sign in again.')
      navigate('/login', { replace: true })
    }
  }, [aal1AccessToken, factorId, navigate])

  const handleCodeChange = (index: number, value: string) => {
    // Only allow digits
    const sanitizedValue = value.replace(/[^0-9]/g, '')

    if (sanitizedValue.length <= 1) {
      const newCodes = [...codes]
      newCodes[index] = sanitizedValue
      setCodes(newCodes)

      // Auto-focus next input
      if (sanitizedValue && index < 5) {
        inputRefs.current[index + 1]?.focus()
      }
    }
  }

  const handleKeyDown = (index: number, e: React.KeyboardEvent) => {
    if (e.key === 'Backspace' && !codes[index] && index > 0) {
      inputRefs.current[index - 1]?.focus()
    }
  }

  const handlePaste = (e: React.ClipboardEvent) => {
    e.preventDefault()
    const pastedText = e.clipboardData.getData('text').replace(/[^0-9]/g, '')
    const pastedCodes = pastedText.split('').slice(0, 6)

    const newCodes = [...codes]
    pastedCodes.forEach((code, index) => {
      if (index < 6) newCodes[index] = code
    })
    setCodes(newCodes)

    const nextEmptyIndex = newCodes.findIndex((code) => !code)
    const focusIndex = nextEmptyIndex === -1 ? 5 : Math.min(nextEmptyIndex, 5)
    inputRefs.current[focusIndex]?.focus()
  }

  const handleVerify = async () => {
    const code = codes.join('')
    if (code.length !== 6 || !aal1AccessToken || !factorId) return

    setIsLoading(true)
    try {
      // Server-side MFA verification via auth-gateway
      // Creates TOTP challenge + verifies code + returns full aal2 session
      await verifyMfaWithGateway({ aal1AccessToken, factorId, code })
      toast.success('Signed in successfully')
      navigate('/today', { replace: true })
    } catch (error: any) {
      console.error('2FA verification failed:', error)
      toast.error(error?.message || 'Invalid code. Please try again.')
      // Clear codes so user can re-enter
      setCodes(['', '', '', '', '', ''])
      inputRefs.current[0]?.focus()
    } finally {
      setIsLoading(false)
    }
  }

  const handleResend = () => {
    // TOTP codes are generated by the authenticator app — there's nothing to "resend".
    // This button is only meaningful for SMS/email OTP flows.
    // For TOTP, we guide the user to their authenticator app instead.
    toast('Open your authenticator app to get a new code.', { icon: '📱' })
    setResendCountdown(30)
  }

  // Auto-submit when all 6 digits are filled
  useEffect(() => {
    if (codes.every((code) => code !== '') && !isLoading) {
      handleVerify()
    }
  }, [codes])

  // Countdown timer for resend button
  useEffect(() => {
    if (resendCountdown > 0) {
      const timer = setTimeout(() => setResendCountdown(resendCountdown - 1), 1000)
      return () => clearTimeout(timer)
    }
  }, [resendCountdown])

  return (
    <div className="relative flex min-h-screen w-full bg-background-dark">
      {/* Back Button */}
      <button
        onClick={() => navigate('/login')}
        className="absolute left-6 top-6 z-10 flex items-center gap-2 text-white/80 transition-colors hover:text-white"
      >
        <span className="material-symbols-outlined">arrow_back</span>
        <span className="text-sm font-medium">Back</span>
      </button>

      {/* Main Container */}
      <div className="relative mx-auto flex w-full max-w-md flex-col justify-center px-6 py-12">
        {/* Header */}
        <div className="mb-8 text-center">
          {/* Logo */}
          <div className="mb-6 inline-block">
            <div className="relative h-20 w-20">
              <div className="absolute inset-1 flex items-center justify-center">
                <svg
                  className="h-full w-full overflow-visible"
                  fill="none"
                  viewBox="0 0 100 100"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <circle
                    cx="50"
                    cy="50"
                    r="46"
                    stroke="#13ec5b"
                    strokeOpacity="0.2"
                    strokeWidth="4"
                  ></circle>
                  <path
                    d="M 50 4 A 46 46 0 1 1 10.7 25.8"
                    stroke="#13ec5b"
                    strokeLinecap="round"
                    strokeWidth="4"
                    fill="none"
                  ></path>
                </svg>
              </div>
              <div className="absolute inset-0 flex items-center justify-center text-primary">
                <span
                  className="material-symbols-outlined text-[#13ec5b]"
                  style={{
                    fontSize: '40px',
                    fontVariationSettings: "'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 48",
                  }}
                >
                  trending_up
                </span>
              </div>
            </div>
          </div>

          <h2 className="mb-1 text-2xl font-bold text-white">HabitFlow</h2>

          <h1 className="mb-4 text-3xl font-bold text-white">Two-factor authentication</h1>
          <p className="mb-2 text-white/80">Enter the 6-digit code from your</p>
          <p className="text-white/80">authenticator app to continue</p>
        </div>

        {/* Form Card */}
        <div className="mb-6 rounded-3xl bg-white p-8 shadow-xl dark:bg-slate-800">
          <div className="space-y-6">
            {/* 6-digit Code Input */}
            <div>
              <div className="mb-6 flex justify-center gap-3" onPaste={handlePaste}>
                {codes.map((code, index) => (
                  <input
                    key={index}
                    ref={(el) => {
                      inputRefs.current[index] = el
                    }}
                    type="text"
                    inputMode="numeric"
                    maxLength={1}
                    autoComplete={index === 0 ? 'one-time-code' : 'off'}
                    value={code}
                    onChange={(e) => handleCodeChange(index, e.target.value)}
                    onKeyDown={(e) => handleKeyDown(index, e)}
                    className="h-12 w-12 rounded-xl border-2 border-slate-200 bg-white text-center text-xl font-bold text-slate-900 transition-colors focus:border-primary focus:outline-none dark:border-slate-700 dark:bg-slate-900 dark:text-white"
                    disabled={isLoading}
                  />
                ))}
              </div>
            </div>

            {/* Verify Button */}
            <button
              type="button"
              onClick={handleVerify}
              disabled={isLoading || codes.some((code) => !code)}
              className="w-full rounded-full bg-primary px-6 py-3 font-semibold text-white transition-all hover:bg-primary-focus active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-50"
            >
              {isLoading ? (
                <span className="flex items-center justify-center gap-2">
                  <span className="material-symbols-outlined animate-spin">progress_activity</span>
                  Verifying…
                </span>
              ) : (
                'Verify'
              )}
            </button>

            {/* Resend / Help Link */}
            <div className="text-center">
              <p className="text-slate-600 dark:text-slate-400">
                Can't find your code?{' '}
                <button
                  type="button"
                  onClick={handleResend}
                  disabled={resendCountdown > 0}
                  className="font-medium text-primary transition-colors hover:underline disabled:cursor-not-allowed disabled:text-slate-400 disabled:no-underline"
                >
                  {resendCountdown > 0
                    ? `Try again (${resendCountdown}s)`
                    : 'Open authenticator app'}
                </button>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
