import type { CategoryTemplatePack } from '@/types/categoryTemplate'

// Category Template Library - Distinct from Task Templates
export const CATEGORY_TEMPLATE_LIBRARY: CategoryTemplatePack[] = [
  {
    id: 'pack_fitness_complete',
    name: 'Complete Fitness System',
    description: 'A comprehensive fitness tracking system with training, nutrition, and recovery',
    icon: 'fitness_center',
    category: 'health',
    color: 'bg-emerald-500',
    tags: ['fitness', 'health', 'workout', 'nutrition'],
    isCustom: false,
    totalCategories: 4,
    totalHabits: 8,
    categories: [
      {
        name: 'Training',
        icon: 'fitness_center',
        color: 'emerald',
        gradient: 'from-emerald-500 to-teal-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Strength Training',
            description: '45 min full-body strength session',
            icon: 'fitness_center',
            frequency: 'weekly',
            goal: 3,
            goalPeriod: 'week',
          },
          {
            name: 'Cardio Workout',
            description: '30 min cardio session',
            icon: 'directions_run',
            frequency: 'weekly',
            goal: 2,
            goalPeriod: 'week',
          },
        ],
      },
      {
        name: 'Mobility',
        icon: 'accessibility_new',
        color: 'indigo',
        gradient: 'from-indigo-500 to-violet-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Morning Stretch',
            description: '10 min mobility routine',
            icon: 'self_improvement',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
        ],
      },
      {
        name: 'Nutrition',
        icon: 'restaurant',
        color: 'yellow',
        gradient: 'from-yellow-400 to-orange-500',
        textColor: 'text-black',
        habits: [
          {
            name: 'Track Meals',
            description: 'Log all meals and snacks',
            icon: 'restaurant_menu',
            frequency: 'daily',
            goal: 3,
            goalPeriod: 'day',
          },
          {
            name: 'Drink Water',
            description: '8 glasses of water',
            icon: 'water_drop',
            frequency: 'daily',
            goal: 8,
            goalPeriod: 'day',
          },
        ],
      },
      {
        name: 'Recovery',
        icon: 'hotel',
        color: 'sky',
        gradient: 'from-sky-400 to-blue-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Sleep 8 Hours',
            description: 'Get quality rest',
            icon: 'bedtime',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
          {
            name: 'Active Recovery',
            description: 'Light walk or yoga',
            icon: 'directions_walk',
            frequency: 'weekly',
            goal: 2,
            goalPeriod: 'week',
          },
        ],
      },
    ],
  },
  {
    id: 'pack_productivity_pro',
    name: 'Productivity Pro',
    description: 'Master your time with deep work, planning, and efficient workflows',
    icon: 'psychology',
    category: 'productivity',
    color: 'bg-purple-500',
    tags: ['productivity', 'work', 'focus', 'planning'],
    isCustom: false,
    totalCategories: 3,
    totalHabits: 6,
    categories: [
      {
        name: 'Deep Work',
        icon: 'timer',
        color: 'purple',
        gradient: 'from-gray-900 to-black dark:from-surface-card dark:to-surface-dark',
        textColor: 'text-white',
        habits: [
          {
            name: 'Focus Block',
            description: '90 min deep work session',
            icon: 'psychology',
            frequency: 'daily',
            goal: 2,
            goalPeriod: 'day',
          },
          {
            name: 'No Distractions',
            description: 'Phone on silent mode',
            icon: 'phone_disabled',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
        ],
      },
      {
        name: 'Planning',
        icon: 'event_note',
        color: 'orange',
        gradient: 'from-orange-500 to-amber-500',
        textColor: 'text-white',
        habits: [
          {
            name: 'Daily Planning',
            description: 'Plan top 3 priorities',
            icon: 'checklist',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
          {
            name: 'Weekly Review',
            description: 'Review and plan the week',
            icon: 'event_note',
            frequency: 'weekly',
            goal: 1,
            goalPeriod: 'week',
          },
        ],
      },
      {
        name: 'Admin',
        icon: 'inventory_2',
        color: 'slate',
        gradient: 'from-slate-600 to-slate-800',
        textColor: 'text-white',
        habits: [
          {
            name: 'Email Inbox',
            description: 'Process all emails',
            icon: 'inbox',
            frequency: 'daily',
            goal: 2,
            goalPeriod: 'day',
          },
          {
            name: 'Organize Files',
            description: 'Clean up workspace',
            icon: 'folder_open',
            frequency: 'weekly',
            goal: 1,
            goalPeriod: 'week',
          },
        ],
      },
    ],
  },
  {
    id: 'pack_mindfulness_wellness',
    name: 'Mindfulness & Wellness',
    description: 'Cultivate peace and balance with meditation, journaling, and self-care',
    icon: 'self_improvement',
    category: 'health',
    color: 'bg-teal-500',
    tags: ['mindfulness', 'wellness', 'meditation', 'self-care'],
    isCustom: false,
    totalCategories: 3,
    totalHabits: 6,
    categories: [
      {
        name: 'Mindfulness',
        icon: 'self_improvement',
        color: 'teal',
        gradient: 'from-teal-500 to-emerald-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Morning Meditation',
            description: '15 min mindfulness practice',
            icon: 'spa',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
          {
            name: 'Breathing Exercise',
            description: '5 min deep breathing',
            icon: 'air',
            frequency: 'daily',
            goal: 2,
            goalPeriod: 'day',
          },
        ],
      },
      {
        name: 'Journaling',
        icon: 'edit_note',
        color: 'pink',
        gradient: 'from-pink-500 to-rose-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Gratitude Journal',
            description: 'Write 3 things you\'re grateful for',
            icon: 'favorite',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
          {
            name: 'Reflection',
            description: 'Evening reflection',
            icon: 'psychology',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
        ],
      },
      {
        name: 'Self-Care',
        icon: 'spa',
        color: 'violet',
        gradient: 'from-violet-500 to-purple-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Skincare Routine',
            description: 'Morning and evening skincare',
            icon: 'face',
            frequency: 'daily',
            goal: 2,
            goalPeriod: 'day',
          },
          {
            name: 'Relaxation Time',
            description: '30 min me-time',
            icon: 'weekend',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
        ],
      },
    ],
  },
  {
    id: 'pack_learning_growth',
    name: 'Learning & Growth',
    description: 'Accelerate your personal development with reading, courses, and skill practice',
    icon: 'school',
    category: 'learning',
    color: 'bg-blue-500',
    tags: ['learning', 'education', 'growth', 'skills'],
    isCustom: false,
    totalCategories: 3,
    totalHabits: 6,
    categories: [
      {
        name: 'Reading',
        icon: 'menu_book',
        color: 'blue',
        gradient: 'from-blue-500 to-cyan-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Daily Reading',
            description: 'Read for 30 minutes',
            icon: 'book',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
          {
            name: 'Finish Book',
            description: 'Complete one book',
            icon: 'auto_stories',
            frequency: 'monthly',
            goal: 1,
            goalPeriod: 'month',
          },
        ],
      },
      {
        name: 'Online Courses',
        icon: 'school',
        color: 'indigo',
        gradient: 'from-indigo-500 to-blue-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Course Lesson',
            description: 'Complete one lesson',
            icon: 'play_circle',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
          {
            name: 'Practice Exercise',
            description: 'Apply what you learned',
            icon: 'code',
            frequency: 'weekly',
            goal: 3,
            goalPeriod: 'week',
          },
        ],
      },
      {
        name: 'Skill Practice',
        icon: 'piano',
        color: 'amber',
        gradient: 'from-amber-500 to-yellow-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Practice Skill',
            description: 'Deliberate practice session',
            icon: 'sports_score',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
          {
            name: 'Track Progress',
            description: 'Review your improvement',
            icon: 'trending_up',
            frequency: 'weekly',
            goal: 1,
            goalPeriod: 'week',
          },
        ],
      },
    ],
  },
  {
    id: 'pack_creative_flow',
    name: 'Creative Flow',
    description: 'Nurture your creativity with art, writing, and creative projects',
    icon: 'palette',
    category: 'personal',
    color: 'bg-rose-500',
    tags: ['creativity', 'art', 'writing', 'projects'],
    isCustom: false,
    totalCategories: 3,
    totalHabits: 6,
    categories: [
      {
        name: 'Writing',
        icon: 'edit',
        color: 'rose',
        gradient: 'from-rose-500 to-pink-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Daily Writing',
            description: 'Write 500 words',
            icon: 'article',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
          {
            name: 'Edit Draft',
            description: 'Review and edit',
            icon: 'edit_note',
            frequency: 'weekly',
            goal: 2,
            goalPeriod: 'week',
          },
        ],
      },
      {
        name: 'Art & Design',
        icon: 'palette',
        color: 'fuchsia',
        gradient: 'from-fuchsia-500 to-purple-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Sketch Daily',
            description: '20 min drawing practice',
            icon: 'draw',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
          {
            name: 'Design Project',
            description: 'Work on creative project',
            icon: 'design_services',
            frequency: 'weekly',
            goal: 3,
            goalPeriod: 'week',
          },
        ],
      },
      {
        name: 'Music',
        icon: 'music_note',
        color: 'cyan',
        gradient: 'from-cyan-500 to-blue-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Practice Instrument',
            description: '30 min practice session',
            icon: 'piano',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
          {
            name: 'Learn New Song',
            description: 'Master a new piece',
            icon: 'library_music',
            frequency: 'monthly',
            goal: 1,
            goalPeriod: 'month',
          },
        ],
      },
    ],
  },
  {
    id: 'pack_social_connections',
    name: 'Social Connections',
    description: 'Strengthen relationships with family, friends, and your community',
    icon: 'people',
    category: 'lifestyle',
    color: 'bg-orange-500',
    tags: ['social', 'relationships', 'family', 'friends'],
    isCustom: false,
    totalCategories: 3,
    totalHabits: 6,
    categories: [
      {
        name: 'Family Time',
        icon: 'family_restroom',
        color: 'orange',
        gradient: 'from-orange-500 to-red-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Family Dinner',
            description: 'Eat together without devices',
            icon: 'restaurant',
            frequency: 'daily',
            goal: 1,
            goalPeriod: 'day',
          },
          {
            name: 'Quality Time',
            description: 'Dedicated family activity',
            icon: 'celebration',
            frequency: 'weekly',
            goal: 1,
            goalPeriod: 'week',
          },
        ],
      },
      {
        name: 'Friendships',
        icon: 'people',
        color: 'lime',
        gradient: 'from-lime-500 to-green-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Reach Out',
            description: 'Call or text a friend',
            icon: 'call',
            frequency: 'weekly',
            goal: 3,
            goalPeriod: 'week',
          },
          {
            name: 'Social Activity',
            description: 'Meet up with friends',
            icon: 'coffee',
            frequency: 'weekly',
            goal: 1,
            goalPeriod: 'week',
          },
        ],
      },
      {
        name: 'Community',
        icon: 'volunteer_activism',
        color: 'green',
        gradient: 'from-green-500 to-emerald-600',
        textColor: 'text-white',
        habits: [
          {
            name: 'Volunteer',
            description: 'Give back to community',
            icon: 'favorite',
            frequency: 'monthly',
            goal: 1,
            goalPeriod: 'month',
          },
          {
            name: 'Community Event',
            description: 'Attend local gathering',
            icon: 'groups',
            frequency: 'monthly',
            goal: 1,
            goalPeriod: 'month',
          },
        ],
      },
    ],
  },
]
