import type { Category } from '@/types/category'

// Deterministic defaults (do not use Date.now here; store can override createdAt if needed)
const DEFAULT_CREATED_AT = '2026-01-01T00:00:00.000Z'

const ZERO_STATS = {
  habitCount: 0,
  taskCount: 0,
  completionRate: 0,
} as const

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'morning-routine',
    name: 'Morning Routine',
    icon: 'wb_sunny',
    color: 'primary',
    gradient: 'from-gray-900 to-black dark:from-surface-card dark:to-surface-dark',
    textColor: 'text-white',
    isPinned: true,
    order: 1,
    createdAt: DEFAULT_CREATED_AT,
    stats: { ...ZERO_STATS },
  },
  {
    id: 'work-projects',
    name: 'Work Projects',
    icon: 'work',
    color: 'blue',
    gradient: 'from-gray-100 to-white dark:from-surface-card dark:to-surface-dark',
    textColor: 'text-black dark:text-white',
    isPinned: true,
    order: 2,
    createdAt: DEFAULT_CREATED_AT,
    stats: { ...ZERO_STATS },
  },
  {
    id: 'fitness',
    name: 'Fitness',
    icon: 'directions_run',
    color: 'emerald',
    height: 'h-auto',
    isPinned: false,
    order: 3,
    createdAt: DEFAULT_CREATED_AT,
    stats: { ...ZERO_STATS },
  },
  {
    id: 'zen',
    name: 'Zen',
    icon: 'self_improvement',
    color: 'purple',
    height: 'h-36',
    isPinned: false,
    order: 4,
    createdAt: DEFAULT_CREATED_AT,
    stats: { ...ZERO_STATS },
  },
  {
    id: 'finance',
    name: 'Finance',
    icon: 'attach_money',
    color: 'yellow',
    height: 'h-40',
    isPinned: false,
    order: 5,
    createdAt: DEFAULT_CREATED_AT,
    stats: { ...ZERO_STATS },
  },
  {
    id: 'reading',
    name: 'Read List',
    icon: 'menu_book',
    color: 'orange',
    height: 'h-56',
    isPinned: false,
    order: 6,
    createdAt: DEFAULT_CREATED_AT,
    stats: { ...ZERO_STATS },
  },
  {
    id: 'learning',
    name: 'Learning',
    icon: 'school',
    color: 'indigo',
    height: 'h-auto',
    isPinned: false,
    order: 7,
    createdAt: DEFAULT_CREATED_AT,
    stats: { ...ZERO_STATS },
  },
  {
    id: 'home',
    name: 'Home',
    icon: 'home',
    color: 'pink',
    height: 'h-auto',
    isPinned: false,
    order: 8,
    createdAt: DEFAULT_CREATED_AT,
    stats: { ...ZERO_STATS },
  },
  {
    id: 'health',
    name: 'Health',
    icon: 'favorite',
    color: 'red',
    height: 'h-auto',
    isPinned: false,
    order: 9,
    createdAt: DEFAULT_CREATED_AT,
    stats: { ...ZERO_STATS },
  },
  {
    id: 'social',
    name: 'Social',
    icon: 'groups',
    color: 'teal',
    height: 'h-36',
    isPinned: false,
    order: 10,
    createdAt: DEFAULT_CREATED_AT,
    stats: { ...ZERO_STATS },
  },
  {
    id: 'work',
    name: 'Work',
    icon: 'business_center',
    color: 'slate',
    height: 'h-auto',
    isPinned: false,
    order: 11,
    createdAt: DEFAULT_CREATED_AT,
    stats: { ...ZERO_STATS },
  },
  {
    id: 'outdoor',
    name: 'Outdoor',
    icon: 'hiking',
    color: 'sky',
    height: 'h-40',
    gradient: 'from-sky-400 to-blue-600',
    isPinned: false,
    order: 12,
    createdAt: DEFAULT_CREATED_AT,
    stats: { ...ZERO_STATS },
  },
]
