import type { TaskTemplate } from '@/types/taskTemplate'

export const DEFAULT_TEMPLATES: TaskTemplate[] = [
  {
    id: 'tmpl_meeting',
    name: 'Meeting',
    description: 'Schedule and prepare for a meeting',
    icon: 'groups',
    category: 'Work',
    color: 'bg-blue-500',
    isCustom: false,
    template: {
      title: 'Team Meeting',
      description: 'Prepare agenda and meeting materials',
      priority: 'medium',
      status: 'todo',
      category: 'Work',
      tags: ['meeting', 'team'],
      subtasks: [
        { text: 'Create meeting agenda', completed: false },
        { text: 'Send calendar invite', completed: false },
        { text: 'Prepare presentation materials', completed: false },
        { text: 'Review previous meeting notes', completed: false },
      ],
      timeEstimate: 60,
    },
  },
  {
    id: 'tmpl_code_review',
    name: 'Code Review',
    description: 'Review pull requests and provide feedback',
    icon: 'code',
    category: 'Work',
    color: 'bg-purple-500',
    isCustom: false,
    template: {
      title: 'Code Review',
      description: 'Review team pull requests',
      priority: 'high',
      status: 'todo',
      category: 'Work',
      tags: ['code', 'review', 'development'],
      subtasks: [
        { text: 'Check code style and conventions', completed: false },
        { text: 'Test functionality', completed: false },
        { text: 'Review test coverage', completed: false },
        { text: 'Provide constructive feedback', completed: false },
        { text: 'Approve or request changes', completed: false },
      ],
      timeEstimate: 45,
    },
  },
  {
    id: 'tmpl_blog_post',
    name: 'Blog Post',
    description: 'Write and publish a blog article',
    icon: 'article',
    category: 'Work',
    color: 'bg-green-500',
    isCustom: false,
    template: {
      title: 'Write Blog Post',
      description: 'Create new blog article',
      priority: 'medium',
      status: 'todo',
      category: 'Work',
      tags: ['writing', 'content', 'blog'],
      subtasks: [
        { text: 'Research topic', completed: false },
        { text: 'Create outline', completed: false },
        { text: 'Write first draft', completed: false },
        { text: 'Add images and media', completed: false },
        { text: 'Edit and proofread', completed: false },
        { text: 'Publish and promote', completed: false },
      ],
      timeEstimate: 180,
    },
  },
  {
    id: 'tmpl_workout',
    name: 'Workout',
    description: 'Exercise and fitness routine',
    icon: 'fitness_center',
    category: 'Personal',
    color: 'bg-red-500',
    isCustom: false,
    template: {
      title: 'Workout Session',
      description: 'Complete daily exercise routine',
      priority: 'high',
      status: 'todo',
      category: 'Personal',
      tags: ['health', 'fitness', 'exercise'],
      subtasks: [
        { text: 'Warm-up (5-10 mins)', completed: false },
        { text: 'Cardio exercises', completed: false },
        { text: 'Strength training', completed: false },
        { text: 'Cool down and stretching', completed: false },
      ],
      timeEstimate: 60,
      recurring: 'daily',
    },
  },
  {
    id: 'tmpl_grocery',
    name: 'Grocery Shopping',
    description: 'Plan and shop for groceries',
    icon: 'shopping_cart',
    category: 'Personal',
    color: 'bg-orange-500',
    isCustom: false,
    template: {
      title: 'Grocery Shopping',
      description: 'Weekly grocery shopping',
      priority: 'medium',
      status: 'todo',
      category: 'Personal',
      tags: ['shopping', 'errands', 'food'],
      subtasks: [
        { text: 'Check pantry and fridge', completed: false },
        { text: 'Make shopping list', completed: false },
        { text: 'Buy vegetables and fruits', completed: false },
        { text: 'Buy proteins and dairy', completed: false },
        { text: 'Buy pantry staples', completed: false },
      ],
      timeEstimate: 90,
      recurring: 'weekly',
    },
  },
  {
    id: 'tmpl_study',
    name: 'Study Session',
    description: 'Focused learning and study time',
    icon: 'school',
    category: 'Personal',
    color: 'bg-indigo-500',
    isCustom: false,
    template: {
      title: 'Study Session',
      description: 'Dedicated time for learning',
      priority: 'high',
      status: 'todo',
      category: 'Personal',
      tags: ['learning', 'education', 'study'],
      subtasks: [
        { text: 'Review previous materials', completed: false },
        { text: 'Read new chapter/content', completed: false },
        { text: 'Take notes', completed: false },
        { text: 'Practice exercises', completed: false },
        { text: 'Review and summarize', completed: false },
      ],
      timeEstimate: 120,
    },
  },
  {
    id: 'tmpl_cleaning',
    name: 'House Cleaning',
    description: 'Clean and organize home',
    icon: 'cleaning_services',
    category: 'Personal',
    color: 'bg-teal-500',
    isCustom: false,
    template: {
      title: 'House Cleaning',
      description: 'Deep clean and organize',
      priority: 'low',
      status: 'todo',
      category: 'Personal',
      tags: ['cleaning', 'home', 'chores'],
      subtasks: [
        { text: 'Vacuum and mop floors', completed: false },
        { text: 'Clean kitchen', completed: false },
        { text: 'Clean bathrooms', completed: false },
        { text: 'Dust surfaces', completed: false },
        { text: 'Take out trash', completed: false },
      ],
      timeEstimate: 90,
      recurring: 'weekly',
    },
  },
  {
    id: 'tmpl_bug_fix',
    name: 'Bug Fix',
    description: 'Investigate and fix a software bug',
    icon: 'bug_report',
    category: 'Work',
    color: 'bg-red-600',
    isCustom: false,
    template: {
      title: 'Fix Bug',
      description: 'Investigate and resolve issue',
      priority: 'high',
      status: 'todo',
      category: 'Work',
      tags: ['bug', 'development', 'urgent'],
      subtasks: [
        { text: 'Reproduce the bug', completed: false },
        { text: 'Identify root cause', completed: false },
        { text: 'Write fix', completed: false },
        { text: 'Test the fix', completed: false },
        { text: 'Create pull request', completed: false },
      ],
      timeEstimate: 90,
    },
  },
  {
    id: 'tmpl_project_planning',
    name: 'Project Planning',
    description: 'Plan and organize a new project',
    icon: 'account_tree',
    category: 'Work',
    color: 'bg-cyan-500',
    isCustom: false,
    template: {
      title: 'Project Planning',
      description: 'Define scope and create project plan',
      priority: 'high',
      status: 'todo',
      category: 'Work',
      tags: ['planning', 'project', 'management'],
      subtasks: [
        { text: 'Define project goals', completed: false },
        { text: 'Identify stakeholders', completed: false },
        { text: 'Break down into tasks', completed: false },
        { text: 'Estimate timeline', completed: false },
        { text: 'Assign responsibilities', completed: false },
        { text: 'Create project documentation', completed: false },
      ],
      timeEstimate: 180,
    },
  },
  {
    id: 'tmpl_reading',
    name: 'Reading Time',
    description: 'Dedicated time for reading',
    icon: 'menu_book',
    category: 'Personal',
    color: 'bg-amber-500',
    isCustom: false,
    template: {
      title: 'Reading Session',
      description: 'Time to read and learn',
      priority: 'low',
      status: 'todo',
      category: 'Personal',
      tags: ['reading', 'learning', 'books'],
      subtasks: [
        { text: 'Find quiet space', completed: false },
        { text: 'Read chapter', completed: false },
        { text: 'Take notes on key insights', completed: false },
        { text: 'Reflect on learnings', completed: false },
      ],
      timeEstimate: 60,
      recurring: 'daily',
    },
  },
]
