import type { TaskTemplate } from '@/types/taskTemplate'

export const DEFAULT_TEMPLATES: TaskTemplate[] = [
  {
    id: 'tmpl_meeting',
    name: 'Meeting',
    description: 'Schedule and prepare for a meeting',
    icon: 'groups',
    category: 'Work',
    color: 'bg-blue-500',
    isCustom: false,
    template: {
      title: 'Team Meeting',
      description: 'Prepare agenda and meeting materials',
      priority: 'medium',
      status: 'todo',
      category: 'Work',
      tags: ['meeting', 'team'],
      subtasks: [
        { text: 'Create meeting agenda', completed: false },
        { text: 'Send calendar invite', completed: false },
        { text: 'Prepare presentation materials', completed: false },
        { text: 'Review previous meeting notes', completed: false },
      ],
      timeEstimate: 60,
    },
  },
  {
    id: 'tmpl_code_review',
    name: 'Code Review',
    description: 'Review pull requests and provide feedback',
    icon: 'code',
    category: 'Work',
    color: 'bg-purple-500',
    isCustom: false,
    template: {
      title: 'Code Review',
      description: 'Review team pull requests',
      priority: 'high',
      status: 'todo',
      category: 'Work',
      tags: ['code', 'review', 'development'],
      subtasks: [
        { text: 'Check code style and conventions', completed: false },
        { text: 'Test functionality', completed: false },
        { text: 'Review test coverage', completed: false },
        { text: 'Provide constructive feedback', completed: false },
        { text: 'Approve or request changes', completed: false },
      ],
      timeEstimate: 45,
    },
  },
  {
    id: 'tmpl_blog_post',
    name: 'Blog Post',
    description: 'Write and publish a blog article',
    icon: 'article',
    category: 'Work',
    color: 'bg-green-500',
    isCustom: false,
    template: {
      title: 'Write Blog Post',
      description: 'Create new blog article',
      priority: 'medium',
      status: 'todo',
      category: 'Work',
      tags: ['writing', 'content', 'blog'],
      subtasks: [
        { text: 'Research topic', completed: false },
        { text: 'Create outline', completed: false },
        { text: 'Write first draft', completed: false },
        { text: 'Add images and media', completed: false },
        { text: 'Edit and proofread', completed: false },
        { text: 'Publish and promote', completed: false },
      ],
      timeEstimate: 180,
    },
  },
  {
    id: 'tmpl_workout',
    name: 'Workout',
    description: 'Exercise and fitness routine',
    icon: 'fitness_center',
    category: 'Personal',
    color: 'bg-red-500',
    isCustom: false,
    template: {
      title: 'Workout Session',
      description: 'Complete daily exercise routine',
      priority: 'high',
      status: 'todo',
      category: 'Personal',
      tags: ['health', 'fitness', 'exercise'],
      subtasks: [
        { text: 'Warm-up (5-10 mins)', completed: false },
        { text: 'Cardio exercises', completed: false },
        { text: 'Strength training', completed: false },
        { text: 'Cool down and stretching', completed: false },
      ],
      timeEstimate: 60,
      recurring: 'daily',
    },
  },
  {
    id: 'tmpl_grocery',
    name: 'Grocery Shopping',
    description: 'Plan and shop for groceries',
    icon: 'shopping_cart',
    category: 'Personal',
    color: 'bg-orange-500',
    isCustom: false,
    template: {
      title: 'Grocery Shopping',
      description: 'Weekly grocery shopping',
      priority: 'medium',
      status: 'todo',
      category: 'Personal',
      tags: ['shopping', 'errands', 'food'],
      subtasks: [
        { text: 'Check pantry and fridge', completed: false },
        { text: 'Make shopping list', completed: false },
        { text: 'Buy vegetables and fruits', completed: false },
        { text: 'Buy proteins and dairy', completed: false },
        { text: 'Buy pantry staples', completed: false },
      ],
      timeEstimate: 90,
      recurring: 'weekly',
    },
  },
  {
    id: 'tmpl_study',
    name: 'Study Session',
    description: 'Focused learning and study time',
    icon: 'school',
    category: 'Personal',
    color: 'bg-indigo-500',
    isCustom: false,
    template: {
      title: 'Study Session',
      description: 'Dedicated time for learning',
      priority: 'high',
      status: 'todo',
      category: 'Personal',
      tags: ['learning', 'education', 'study'],
      subtasks: [
        { text: 'Review previous materials', completed: false },
        { text: 'Read new chapter/content', completed: false },
        { text: 'Take notes', completed: false },
        { text: 'Practice exercises', completed: false },
        { text: 'Review and summarize', completed: false },
      ],
      timeEstimate: 120,
    },
  },
  {
    id: 'tmpl_cleaning',
    name: 'House Cleaning',
    description: 'Clean and organize home',
    icon: 'cleaning_services',
    category: 'Personal',
    color: 'bg-teal-500',
    isCustom: false,
    template: {
      title: 'House Cleaning',
      description: 'Deep clean and organize',
      priority: 'low',
      status: 'todo',
      category: 'Personal',
      tags: ['cleaning', 'home', 'chores'],
      subtasks: [
        { text: 'Vacuum and mop floors', completed: false },
        { text: 'Clean kitchen', completed: false },
        { text: 'Clean bathrooms', completed: false },
        { text: 'Dust surfaces', completed: false },
        { text: 'Take out trash', completed: false },
      ],
      timeEstimate: 90,
      recurring: 'weekly',
    },
  },
  {
    id: 'tmpl_bug_fix',
    name: 'Bug Fix',
    description: 'Investigate and fix a software bug',
    icon: 'bug_report',
    category: 'Work',
    color: 'bg-red-600',
    isCustom: false,
    template: {
      title: 'Fix Bug',
      description: 'Investigate and resolve issue',
      priority: 'high',
      status: 'todo',
      category: 'Work',
      tags: ['bug', 'development', 'urgent'],
      subtasks: [
        { text: 'Reproduce the bug', completed: false },
        { text: 'Identify root cause', completed: false },
        { text: 'Write fix', completed: false },
        { text: 'Test the fix', completed: false },
        { text: 'Create pull request', completed: false },
      ],
      timeEstimate: 90,
    },
  },
  {
    id: 'tmpl_project_planning',
    name: 'Project Planning',
    description: 'Plan and organize a new project',
    icon: 'account_tree',
    category: 'Work',
    color: 'bg-cyan-500',
    isCustom: false,
    template: {
      title: 'Project Planning',
      description: 'Define scope and create project plan',
      priority: 'high',
      status: 'todo',
      category: 'Work',
      tags: ['planning', 'project', 'management'],
      subtasks: [
        { text: 'Define project goals', completed: false },
        { text: 'Identify stakeholders', completed: false },
        { text: 'Break down into tasks', completed: false },
        { text: 'Estimate timeline', completed: false },
        { text: 'Assign responsibilities', completed: false },
        { text: 'Create project documentation', completed: false },
      ],
      timeEstimate: 180,
    },
  },
  {
    id: 'tmpl_reading',
    name: 'Reading Time',
    description: 'Dedicated time for reading',
    icon: 'menu_book',
    category: 'Personal',
    color: 'bg-amber-500',
    isCustom: false,
    template: {
      title: 'Reading Session',
      description: 'Time to read and learn',
      priority: 'low',
      status: 'todo',
      category: 'Personal',
      tags: ['reading', 'learning', 'books'],
      subtasks: [
        { text: 'Find quiet space', completed: false },
        { text: 'Read chapter', completed: false },
        { text: 'Take notes on key insights', completed: false },
        { text: 'Reflect on learnings', completed: false },
      ],
      timeEstimate: 60,
      recurring: 'daily',
    },
  },
  {
    id: 'tmpl_email_inbox',
    name: 'Email Inbox Zero',
    description: 'Process and organize emails',
    icon: 'mail',
    category: 'Work',
    color: 'bg-sky-500',
    isCustom: false,
    template: {
      title: 'Email Inbox Zero',
      description: 'Clear and organize email inbox',
      priority: 'medium',
      status: 'todo',
      category: 'Work',
      tags: ['email', 'productivity', 'organization'],
      subtasks: [
        { text: 'Sort emails by priority', completed: false },
        { text: 'Respond to urgent emails', completed: false },
        { text: 'Archive or delete old emails', completed: false },
        { text: 'Unsubscribe from unwanted lists', completed: false },
        { text: 'Create folders and filters', completed: false },
      ],
      timeEstimate: 45,
      recurring: 'daily',
    },
  },
  {
    id: 'tmpl_social_media',
    name: 'Social Media Post',
    description: 'Create and schedule social media content',
    icon: 'share',
    category: 'Work',
    color: 'bg-pink-500',
    isCustom: false,
    template: {
      title: 'Social Media Post',
      description: 'Plan and publish social content',
      priority: 'medium',
      status: 'todo',
      category: 'Work',
      tags: ['social', 'marketing', 'content'],
      subtasks: [
        { text: 'Research trending topics', completed: false },
        { text: 'Create engaging caption', completed: false },
        { text: 'Design or select visuals', completed: false },
        { text: 'Schedule post', completed: false },
        { text: 'Engage with comments', completed: false },
      ],
      timeEstimate: 30,
    },
  },
  {
    id: 'tmpl_meal_prep',
    name: 'Meal Prep',
    description: 'Plan and prepare meals for the week',
    icon: 'restaurant',
    category: 'Personal',
    color: 'bg-lime-500',
    isCustom: false,
    template: {
      title: 'Weekly Meal Prep',
      description: 'Prepare healthy meals in advance',
      priority: 'medium',
      status: 'todo',
      category: 'Personal',
      tags: ['cooking', 'health', 'food'],
      subtasks: [
        { text: 'Plan weekly menu', completed: false },
        { text: 'Make grocery list', completed: false },
        { text: 'Shop for ingredients', completed: false },
        { text: 'Prep vegetables', completed: false },
        { text: 'Cook main dishes', completed: false },
        { text: 'Portion into containers', completed: false },
      ],
      timeEstimate: 180,
      recurring: 'weekly',
    },
  },
  {
    id: 'tmpl_presentation',
    name: 'Presentation',
    description: 'Create and deliver a presentation',
    icon: 'slideshow',
    category: 'Work',
    color: 'bg-violet-500',
    isCustom: false,
    template: {
      title: 'Prepare Presentation',
      description: 'Create slides and practice delivery',
      priority: 'high',
      status: 'todo',
      category: 'Work',
      tags: ['presentation', 'public speaking', 'slides'],
      subtasks: [
        { text: 'Define key message', completed: false },
        { text: 'Create outline', completed: false },
        { text: 'Design slides', completed: false },
        { text: 'Add data and visuals', completed: false },
        { text: 'Practice delivery', completed: false },
        { text: 'Prepare for Q&A', completed: false },
      ],
      timeEstimate: 240,
    },
  },
  {
    id: 'tmpl_meditation',
    name: 'Meditation',
    description: 'Mindfulness and meditation practice',
    icon: 'self_improvement',
    category: 'Personal',
    color: 'bg-purple-400',
    isCustom: false,
    template: {
      title: 'Meditation Session',
      description: 'Practice mindfulness and relaxation',
      priority: 'medium',
      status: 'todo',
      category: 'Personal',
      tags: ['mindfulness', 'health', 'wellness'],
      subtasks: [
        { text: 'Find quiet space', completed: false },
        { text: 'Set timer (10-20 mins)', completed: false },
        { text: 'Focus on breathing', completed: false },
        { text: 'Practice body scan', completed: false },
        { text: 'Journal reflections', completed: false },
      ],
      timeEstimate: 20,
      recurring: 'daily',
    },
  },
  {
    id: 'tmpl_networking',
    name: 'Networking',
    description: 'Connect with professionals',
    icon: 'groups_2',
    category: 'Work',
    color: 'bg-emerald-500',
    isCustom: false,
    template: {
      title: 'Professional Networking',
      description: 'Build and maintain professional relationships',
      priority: 'low',
      status: 'todo',
      category: 'Work',
      tags: ['networking', 'career', 'relationships'],
      subtasks: [
        { text: 'Update LinkedIn profile', completed: false },
        { text: 'Reach out to 3 connections', completed: false },
        { text: 'Attend virtual/in-person event', completed: false },
        { text: 'Follow up with recent contacts', completed: false },
        { text: 'Share valuable content', completed: false },
      ],
      timeEstimate: 60,
      recurring: 'weekly',
    },
  },
  {
    id: 'tmpl_financial_review',
    name: 'Financial Review',
    description: 'Review and manage personal finances',
    icon: 'account_balance',
    category: 'Personal',
    color: 'bg-green-600',
    isCustom: false,
    template: {
      title: 'Monthly Financial Review',
      description: 'Track expenses and budget',
      priority: 'high',
      status: 'todo',
      category: 'Personal',
      tags: ['finance', 'budget', 'money'],
      subtasks: [
        { text: 'Review bank statements', completed: false },
        { text: 'Categorize expenses', completed: false },
        { text: 'Update budget spreadsheet', completed: false },
        { text: 'Pay bills', completed: false },
        { text: 'Review savings goals', completed: false },
        { text: 'Plan next month budget', completed: false },
      ],
      timeEstimate: 90,
      recurring: 'monthly',
    },
  },
  {
    id: 'tmpl_side_project',
    name: 'Side Project Work',
    description: 'Dedicated time for personal projects',
    icon: 'lightbulb',
    category: 'Personal',
    color: 'bg-yellow-500',
    isCustom: false,
    template: {
      title: 'Side Project Session',
      description: 'Work on personal project',
      priority: 'medium',
      status: 'todo',
      category: 'Personal',
      tags: ['project', 'creativity', 'learning'],
      subtasks: [
        { text: 'Review project roadmap', completed: false },
        { text: 'Work on current milestone', completed: false },
        { text: 'Test new features', completed: false },
        { text: 'Document progress', completed: false },
        { text: 'Plan next steps', completed: false },
      ],
      timeEstimate: 120,
    },
  },
  {
    id: 'tmpl_car_maintenance',
    name: 'Car Maintenance',
    description: 'Vehicle inspection and maintenance',
    icon: 'directions_car',
    category: 'Personal',
    color: 'bg-slate-500',
    isCustom: false,
    template: {
      title: 'Car Maintenance Check',
      description: 'Regular vehicle maintenance',
      priority: 'medium',
      status: 'todo',
      category: 'Personal',
      tags: ['car', 'maintenance', 'errands'],
      subtasks: [
        { text: 'Check oil level', completed: false },
        { text: 'Inspect tire pressure', completed: false },
        { text: 'Clean interior and exterior', completed: false },
        { text: 'Check fluid levels', completed: false },
        { text: 'Schedule service if needed', completed: false },
      ],
      timeEstimate: 60,
      recurring: 'monthly',
    },
  },
  {
    id: 'tmpl_portfolio_update',
    name: 'Portfolio Update',
    description: 'Update professional portfolio',
    icon: 'work',
    category: 'Work',
    color: 'bg-indigo-600',
    isCustom: false,
    template: {
      title: 'Update Portfolio',
      description: 'Refresh portfolio with recent work',
      priority: 'low',
      status: 'todo',
      category: 'Work',
      tags: ['portfolio', 'career', 'showcase'],
      subtasks: [
        { text: 'Review current portfolio', completed: false },
        { text: 'Select recent projects', completed: false },
        { text: 'Write project descriptions', completed: false },
        { text: 'Update images/screenshots', completed: false },
        { text: 'Update skills section', completed: false },
        { text: 'Test all links', completed: false },
      ],
      timeEstimate: 150,
    },
  },
]
